version: '1'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      - MYSQL_USER=librarian
      - MYSQL_ROOT_PASSWORD=librarypass
      - MYSQL_DATABASE=library
    networks:
      - project-network
    volumes:
      - /home/abir/db-dump:/docker-entrypoint-initdb.d #add sql file in db-dump
      - /home/abir/docker-compose/db-data:/var/lib/mysql/

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nginx-container
    ports:
      - 80:80
    networks:
      - project-network
    depends_on:
      - mysql
    volumes:
      - /home/abir/docker-compose/nginx-files:/usr/share/nginx/html

networks:
  project-network: